db:
  image: postgres
redis:
  image: redis

box:
  image: busybox
  volumes:
    - /bundle

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
  links:
    - web

sidekiq:
  build: .
  dockerfile: Dockerfile.development
  command: ./scripts/docker-sidekiq-start.sh
  links:
    - db
    - redis
  volumes_from:
    - box
  environment:
    - SECRET_KEY_BASE=secret-key-base
    - RAILS_ENV=development
    - REDIS_URL=redis://redis:6379
    - DATABASE_URL=postgresql://db/postgres?user=postgres&password=postgres

web:
  build: .
  dockerfile: Dockerfile.development
  command: ./scripts/docker-web-start.sh
  links:
    - db
    - redis
  volumes_from:
    - box
  environment:
    - VIRTUAL_HOST=~.
    - VIRTUAL_PORT=3000
    - RAILS_ENV=development
    - REDIS_URL=redis://redis:6379
    - RAILS_SERVE_STATIC_FILES=1
    - DATABASE_URL=postgresql://db/postgres?user=postgres&password=postgres
