db:
  image: postgres
redis:
  image: redis

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "80:80"
  links:
    - web

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml -e production
  links:
    - db
    - redis
  environment:
    - SECRET_KEY_BASE=secret-key-base
    - RAILS_ENV=production
    - REDIS_URL=redis://redis:6379
    - DATABASE_URL=postgresql://db/postgres

web:
  build: .
  command: bundle exec puma -C config/puma.rb -e production
  links:
    - db
    - redis
  environment:
    - VIRTUAL_HOST=~.
    - VIRTUAL_PORT=3000
    - SECRET_KEY_BASE=secret-key-base
    - RAILS_ENV=production
    - REDIS_URL=redis://redis:6379
    - RAILS_SERVE_STATIC_FILES=1
    - DATABASE_URL=postgresql://db/postgres