FROM ruby:2.3.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN gem update --system

RUN mkdir /app

WORKDIR /app

RUN mkdir log
RUN mkdir -p tmp/pids

ENV BUNDLE_PATH=/bundle

ADD . /app

EXPOSE 3000
